title: Personal blog
email: andrewkuleshov7@gmail.com
description: >
  Andrey Kuleshov's blog
name: yegor256.com
url: https://www.akuleshov7.com
baseurl: "/"
twitter_username: test
github_username: akuleshov7
markdown: kramdown
author:
  name: "akuleshov7"
  email: andreykuleshov7@gmail.com
encoding: utf-8
timezone: Europe/Moscow
permalink: :year-:month-:day-:title.html
exclude:
  - README.md
  - Gemfile.lock
  - Gemfile
  - Rakefile
  - LICENSE.txt
  - id_rsa.enc

plugins:
  - jekyll-feed
  - jekyll-bits
  - jekyll-paginate
  - jekyll-plantuml
  - jekyll-sitemap
  - jekyll-redirect-from

paginate: 2
paginate_path: "p/:num"
excerpt_separator: <!--more-->

feed:
  title: akuleshov7.github.io
  subtitle: Personal blog of akuleshov7
  path: rss.xml

sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false
